TCPDataPackageService:
  NetworkInterface: "0.0.0.0"
  IP: "0.0.0.0"
  Port: 8080

SSLDataPackageService:
  NetworkInterface: "0.0.0.0"
  IP: "0.0.0.0"
  Port: 8443

SSLCoTService:
  NetworkInterface: "0.0.0.0"
  Port: 8089

TCPCoTService:
  NetworkInterface: "0.0.0.0"
  Port: 8087

RestAPIService:
  NetworkInterface: "0.0.0.0"
  Port: 14235
  APIKey: None

FederatioServerService:
  NetworkInterface: "0.0.0.0"
  Port: 8283

DataBaseConfiguration:
  DataBasePath: "/opt/FTS/FreeTAKDataBase.db"