CoTServicePort: 15777
SSLCoTServicePort: 8089
DataPackageServiceDefaultIP: '0.0.0.0'
UserConnectionIP: '0.0.0.0'
APIPort: 19023
FederationPort: 9000
APIIP: '0.0.0.0'
SaveCoTToDB: True
DBFilePath: '/root/FTSDataBase.db'
MainPath: 'C:\Users\natha\PycharmProjects\InDev\FreeTAKServerParent\FreeTAKServer'
