name: "FTS Pub Server Rebuild"

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild Pub Server
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ DO_API_TOKEN }}
        run: |
          doctl compute droplet-action restore ${{ DO_PUB_DROPLET_ID }} --image-id ${{ DO_PUB_SNAPSHOT_ID }}