# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package To Dev

on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: set python token
      run: poetry config http-basic.pypi ${{ secrets.DEV_PYPI_USERNAME }} ${{ secrets.DEV_PYPI_PASSWORD }}
    - name: set target repository
      run: poetry config repositories.foo http://${{ secrets.DEV_PYPI_ADDRESS }}:8080
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.1.6
    - name: Setup a local virtual environment (if no poetry.toml file)
      run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}
    - name: Install the project dependencies
      run: poetry install
    - name: build the project
      run: poetry build
    - name: publish the prject
      run: poetry publish

